Pikaday/Pikaday

README.md
pikaday.js

Add options for disabling weekend selection in the calendar and a disableDayFn callback to provide finer grained control over which days are disabled.

Add more options for disabling of calendar days

---

css/pikaday.css

Making the buttons text transparent instead of using the "text-indent" workaround.

---

bower.json

This removes artifacts published to bower that are not needed.

Remove unecessary exports from bower

---

scss/pikaday.scss

* Converting CSS to SCSS syntax; nesting styles when appropriate
* Removing `@charset`; Sass compiler should add this to the output

Creating SCSS option.

---

README.md
css/theme.css
examples/theme.html
pikaday.js

* Accepts a string; returns null otherwise
* Adds the classname to the `pika-single` element
* Classname can then be used in a stylesheet to theme the datepicker (`.pika-single.dark-theme { ... }`)

Adding themeClass option.

---

pikaday.js

when using mobile safari next button, the month select gets focused. this prevents it.

prevent focus on tab navigation

---

README.md
css/pikaday.css
examples/date-range.html
pikaday.js

Date range support

---

scss/pikaday.scss

@nathancahill added range styles to pikaday.css in https://github.com/dbushell/Pikaday/pull/337.
This PR just adds those same styles to pikaday.scss in case anyone prefers to use the scss file for their project. 
@dbushell thanks!

add @nathancahill's range styles to pikaday.scss

---

pikaday.js

Fixes #432. Also makes setMaxDate match setMinDate (setToStartOfDay, maxYear, maxMonth were only being called if set in the options, and not in the function. @rikkert this is tested and good to merge.

Redraw after setMinDate() and setMaxDate()

---

pikaday.js

Make disabled buttons not clickable in IE 10 and below [closes #288]

---

css/pikaday.css

The picker is 100% responsive with a couple of css lines. Please check it out,  I really hope you consider merging.
Best regards, Oli

Made picker 100% responsive

---

pikaday.js

This makes Pikaday XHTML compatible while not making any breaking changes for normal HTML use.
For more information about the selected attribute see: http://stackoverflow.com/a/24588336

Make Pikaday XHTML compatible.

---

README.md
index.html
pikaday.js

First I'd like to give *all* of the credit to @mrenty. He did pretty much all of the hard work on this and I came in to push it over the line. 
Today is Global Accessibility Awareness Day and one of the things I _really_ wanted to do for GAAD was make Pikaday accessibile. With this datepicker being the go to for the majority of the dev community it's important to me that this plugin is accessibile.
Here's a video example of what it's like to use this PRs Pikaday with a screen reader: https://www.youtube.com/watch?v=iZhi4nQP5kI
Here's what it's like to use pikaday with a screen reader today: 
https://youtu.be/mrUwra6C34U
CC: @dbushell / @rikkert

First pass at making Pikaday accessibile

---

css/pikaday.css

Fix pikaday.css, separate selectors with comma so that it builds

pikaday css fix

---

pikaday.js

Fix the (re)position issue, see #643, #642.

fix reposition in show()

---

README.md

A small fix; wrong function name was written by accident.

fix function name

---

README.md

Mentioning the value for `setDefaultDate` is **Boolean**. It is not apparent from the documentation.

Mention type for setDefaultDate option

---

pikaday.js

There will be duplicate ids for `.pika-lendar` is `numberOfMonths > 1`. This PR fixes that issue.

Use a unique id for each month panel.

---

pikaday.js
tests/methods.js

Calculation based on http://weeknumber.net/how-to/javascript but modified it to be a bit more elaborate what all the "magic constants" are about.

Closes #388 - Fix the week number calculation according to ISO8601.

---

scss/pikaday.scss

This is useful in case users don't want border-radius on their calendars.

Make a variable for custom border-radius

---

scss/pikaday.scss

Just a tiny change to allow users to easily change the z-index while using Pikaday's SCSS if they need to.

Made z-index a variable in SCSS
