Pikaday/Pikaday

pikaday.js
Changes in #166 broke the click handler's detection of clicks within the pikaday element; for example, clicking on the date drop-downs, as reported in issues #224 and #230.
This change adds the original conditions to the patch in #166. This fixes the introduced bug, while leaving the #166 changes in place to support trigger child elements.
=> Fix for bug introduced in #166; fixes #224, #230

pikaday.js
Fixes #246 
The `onmousedown` event listener is bound to the `button`, which doesn't have the `is-disabled` class name. To prevent the selection of disabled days, you need to look to the `parentElement` (`td`) for the class.
=> [bugfix] Selecting a disabled day shouldn't change the date

pikaday.js, tests/methods.js
I ran into an issue that is documented in https://github.com/dbushell/Pikaday/issues/254. I believe the issue manifests when setting min date to a date/time that has a time portion (I noticed it using the current date and time) - the draw function will render the first enabled day as the day after what was passed to setMinDate.
I believe this is due to the constructor removing the time portion but setMinDate() preserves the time. This means that the first conditional at https://github.com/dbushell/Pikaday/blob/master/pikaday.js#L948 will evaluate to false for the previously set min date and evaluate true on the day after the supplied minDate.
This change makes the setMinDate behaviour consistent with that of the constructor "minDate" behaviour.
Bit awkward to explain but hopefully the …
=> Make setMinDate() behaviour consistent with the "minDate" option in constructor

pikaday.js
Avoids a Content Security Policy error.
See these two for other examples:
- https://github.com/Modernizr/Modernizr/pull/1263
- https://code.google.com/p/chromium/issues/detail?id=343970
=> Set style directly instead of using `cssText`

pikaday.js
This update let the user to type directly into the input field and keep the content.
Without this change, when the user leave the input field, the input will change to a null value which is bad (as the user loose the content he just put into).
* The user select a date (02-02-2015) with pickaday.
* Then he just want to change the year. Instead of use pickaday again he decide to direclty type into the field and update the 5 into a 6.
* Happy of his quick update, he leave the field.
* Then he loose his selected date
* He's sad.
=> Update pikaday.js to fix accessibility/utilisability issue

pikaday.js
Ran into an issue where the popup was being positioned off the screen.  Tracked the problem down to the way the width was being calculated.  The popup was positioned normally before the width was checked which resulted in a full width div.  This resulted in the left point being very negative.  I moved setting the position to absolute before the variables are set to fix this.
This could also be accomplished by updating the stylesheet.
=> Fix how the width of the popup is calculated.

examples/amd.html, examples/bound-container.html, examples/calendars.html, examples/container.html, examples/jquery-amd.html, examples/jquery.html, examples/moment.html, examples/trigger.html, examples/weeknumbers.html, index.html
The examples use Date constructors like this: `new Date('2000-01-01')`. Date strings without timezone information are parsed as UTC. Internally, Pikaday uses the integer form: `new Date(2000, 0, 1)`, which creates a date with the local timezone. This means the discrepancy of minDate, maxDate, defaultDate, etc. can be up to 12(13?) hours from what's expected.
This causes confusion like #138 and #267, and seemingly off by one bugs (that aren't really bugs) like this [JSFiddle](http://jsfiddle.net/vjmsvn03/) if you load it in UTC-06:00 before noon. Here's a screenshot for others:
Might be good to add a note to the readme too.
=> Change example dates from strings to integers

pikaday.js
Fix for https://github.com/dbushell/Pikaday/issues/374
Credit goes to @kaib84 but I'm doing the PR because of lack of response from that gentleman.
=> Register click and touch event separately

plugins/pikaday.jquery.js
Makes the behavior consistent with vanilla Pikaday (instances can be destroyed and re-created without side effects)
Thanks for reporting #382 @Muffinman
=> Remove jQuery data attribute after Pikaday instance is destroyed

README.md, pikaday.js
Moment's default parser is very forgiving and translates user typed values into unexpected dates.
If the input format is set to "MM/DD/YYYY", and the user inputs "test5" ... Moment will convert the user input into "05/01/2015".
This flag enables Moment's strict parsing.
=> Add options flag for strict date parsing with moment

scss/pikaday.scss
A number of variables have now been added which hold the colours and fonts used in Pikaday. They use the `!default` syntax to allow for overriding before importing the SCSS file. This is similar to how [Bootstrap SASS does it](https://github.com/twbs/bootstrap-sass#sass-1).
For example, I'm using Pikaday in a Rails app. I'm importing the Pikaday SCSS file from its `vendor/components` home, but beforehand I'm setting a few variables to override the defaults. This means I don't need to spend time overriding things and getting into specificity battles (eek `!important`).
Here's a snippet of code from the project I'm using my Pikaday fork in:
```scss
$pd-font-family: Gotham, 'Proxima Nova', 'Helvetica Neue', Arial, sans-serif;
$pd-day-bg: lighten(desaturate($teal, 20%), 60%); …
```
=> Move colours and fonts to variables to allow for easy customising

pikaday.js
The changes allow to **reset the maximum and minimum date**. A typical use case for this feature is when you use two datepicker to select a range and **one or both bounds are optionnal** (the date-range.html example with enhancements). When setting the optional value to null it was not possible to remove the range limitation.
=> Add possibility to reset the max and min date to the date picker.

pikaday.js
https://github.com/dbushell/Pikaday/issues/643
=> fixed, when datepicker opens incorrectly, when page doesn't have scroll

README.md, pikaday.js
By default Pikaday blurs the input field making tabbing across the forms input fields harder.
Added setting `blurFieldOnSelect` which controls if the the field should be blurred.
=> Configure if field is blurred when date is selected

pikaday.js
Fixed issue #611: Pressing enter or escape when no field is bound will cause an error.
After upgrading to latest Pikaday release, lots of exceptions are logged in our application due to this issue.
We had to revert to previous version of Pikaday. 
I have just added a null check that solves this problem.
=> Fixed issue #611: Pressing enter or escape when no field is bound will cause an error.

package.json, pikaday.js, tests/methods.js
The documentation for getDate states it should return "null if no selection". This behaviour was
however changed in https://github.com/dbushell/Pikaday/commit/3f4b9c939016125904f4d1b053e81db064bf02d8#diff-5e6a2e8d597bd0e8a3111ba17c4a0815L699 when enabling keyboard navigation, breaking the API. Revert the change of getDate and modify the keybaord navigation to default to the current time.
As I have not found any documentation on testing, this pull request contains a second commit to make (local) testing and linting available via NPM, in the hope that this will be helpful to new contributors (like me :) ).
=> Fix broken getDate API

README.md, css/pikaday.css, examples/pick-whole-week.html, pikaday.js
I added a new option `pickWholeWeek`. When set to `true`, instead of picking a day, you can pick a whole week. Hope it helps.
Note: I didn't change a lot to the original implementation. Technically you are still picking one day, but the entire row is highlighted. You will need to calculate your week's start and end. See the example for details.
=> Week mode: Pick a whole week instead of a day

plugins/pikaday.jquery.js
In the jQuery plugin there's a `require('../pikaday')` which was causing havoc when I was using browserify and browserify-shim. Removing the `../` seemed to do the trick. Looks unnecessary to have it there in the first place too.
=> jQuery plugin: rename relative path to pikaday to npm package name

README.md, examples/aria-label.html, pikaday.js
This allows to set the `aria-label` text when using the `bound` property, which is now not possible to adjust.
=> Add `aria-label` config option

package.json
As discussed in #718
Otherwise npm will try to install Moment.js (even if it is optional) and because of this, Webpack automatically includes Moment.js in the bundle (Pikaday uses require('moment').
Users who still want to use Moment.js with Pikaday, can manually add it to their package.json file and everything will work as expected.
This change has the benefit that people who use bundle software don't need to change their config to ignore Moment.js and people who do want it usually add it to their package.json anyway.
I don't think I need to make changes to the readme. People who want to use Moment.js can take a look at the moment.js docs for installation instructions.
=> Remove the Moment.js optional dependency from package.json

README.md, examples/position-css-classes.html, examples/positions.html, pikaday.js
This feature allows for the styling of the datepicker to change according to where it is relative to field – for example datepickers that are styled to have a pointer that points to a date-input.
CSS-classnames (open to suggestions):
* `top-aligned`
* `bottom-aligned`
* `left-aligned`
* `right-aligned`
I had some trouble getting your tests and linting to work. If you want me to do something for that then could you give me some pointers on how to get that up and running?
=> Add CSS-classes indicating position

bower.json
As they are not needed in production, so they will not appear in installed package
=> Add tests and examples to bower.json ignores

examples/jquery.html
`<script src="//path">` works great when you run a demo on a local webserver, but opening the demo file on your local will try to find jQuery on `file:///`. Adding `https:` or `http:` makes sure the demo will also run straight out of the zip.
=> Running jQuery demo on local machine

.npmignore
My pikaday 1.4.0 installation contains quite a few files that are not needed for running the code. This `.npmignore` script excludes these files from the package. I was unsure about index.html and CHANGELOG.md, so if you feel they should be included in the packages I'll change my pull request.
=> Remove non-essential files from npm package

pikaday.js
Replace isLeapYear() method with code from a permissive license, due to StackOverflow code being under a more restrictive license (and general ambiguity surrounding using S.O. code).
=> change isLeapYear() to remove stackoverflow code

CHANGELOG.md
I believe 2015-02-17 was a copy and paste typo, might be worth fixing to avoid any confusion
=> Fix 1.3.3 release date in the CHANGELOG

pikaday.js
Disabled tag on the options did not have a space before it meaning it was concatenated with whatever was previously written. This is fine for non-XHTML but Chrome outputs an error about invalid XML : 
"pikaday.js:970 Uncaught SyntaxError: Failed to set the 'innerHTML' property on 'Element': The provided markup is invalid XML, and therefore cannot be inserted into an XML document."
=> Fix the lack of space causing invalid XHTML

pikaday.js
e.preventDefault() removed on left arrow key. This causes issue when using pikaday in combination with other text input fields.
=> e.preventDefault() removed on left arrow key

README.md, pikaday.js
There is a small typo in README.md, pikaday.js.
Should read `text` rather than `tekst`.
=> docs: Fix simple typo, tekst -> text

pikaday.js
Fixes https://github.com/Pikaday/Pikaday/issues/840
When the `container` option is passed position is not set in the `adjustPosition` method but it is still set to `static` in the `hide` method. This makes it so you need to use `position: absolute !important` in your CSS to override the unnecessary inline styles. 
This PR adds the same check that is in `adjustPosition` to the `hide` method
=> Prevent setting `position: static` inline when `container` option is passed

scss/pikaday.scss
I saw the implementation for events https://github.com/Pikaday/Pikaday/pull/152. This is really cool only the scss file was not updated to make use of this feature.
Since I use the scss file to style the datepicker in our project I've added `event-color` and `event-bg` as variables
=> Added has-event styling in scss file

css/pikaday.css
The current text-align: right on the pika-button class causes the calendar (and its contents) to appear unbalanced. Changing pika-button's text-align to center makes the calendar easier to read, and makes better use of horizontal spacing between dates.
=> Center Pika-button Text Alignment

pikaday.js
Screen reader to properly read the selected date on keyboard navigation
Screen reader is being forced to read content of `heading` element, because of `aria-live="assertive"` changing this to `polite` ensures the screen reader to read it after finishing the date change.
https://user-images.githubusercontent.com/6163988/134709516-12fa7c48-14e6-4009-bd50-52a9b418beed.mov
=> fix(accessibility): screen reader being forced to read headings on day change
